### 패딩
+ 데이터 확장하여 경계값 처리
+ constant : 양쪽으로 상수 붙임
+ reflect : 가운데 인덱스 값을 기준으로 반사
+ symmetric : 양쪽 끝 값 기준 반사

+ 1차원 데이터 패딩
+ 2차원 데이터 패딩

In [1]:
import tensorflow as tf
import numpy as np

##### 1차원 패딩

In [6]:
#36_01
#1: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')

#2
p = 2
paddings = np.array([[p, p]])

#3
B = tf.pad(A, paddings, "constant") # 고정값으로 채움 (default 0)
C = tf.pad(A, paddings, "reflect") # 중앙값 기준 반사
D = tf.pad(A, paddings, "symmetric") # 양쪽 끝 기준 반사
print("B=", B.numpy())
print("C=", C.numpy())
print("D=", D.numpy())


B= [0. 0. 1. 2. 3. 4. 5. 0. 0.]
C= [3. 2. 1. 2. 3. 4. 5. 4. 3.]
D= [2. 1. 1. 2. 3. 4. 5. 5. 4.]


In [7]:
#36_02
#1:
def pad1d_infor(steps, kernel_size=2, strides=1,
                  dilation_rate=1, padding= 'valid'):
    k = (kernel_size-1)*dilation_rate + 1
    if padding == 'valid':
        new_steps = int(np.ceil((steps - k + 1) / strides))
        pad_left, pad_right=(0, 0)

    else: # 'same', 'casual'
        new_steps = int(np.ceil(steps/strides))
        pad_width = max((new_steps  - 1) * strides + k - steps, 0)

        if padding == 'same':
            pad_left  = pad_width//2
            pad_right = pad_width - pad_left
        if padding =='casual':
            pad_left  = pad_width
            pad_right = 0
    return k, new_steps, (pad_left, pad_right)

#2: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')
length = A.shape[0] #len(len), 5

#3: padding in MaxPool1D [step37_02]
#3-1:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=2,
                                      strides=2, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B1 = tf.pad(A, paddings=np.array([pads]))
print("B1=", B1.numpy())

#3-2:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=4,
                                      strides=3, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B2 = tf.pad(A, paddings=np.array([pads]))
print("B2=", B2.numpy())

#4: padding in Conv1D
#4-1:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B3 = tf.pad(A, paddings=np.array([pads]))
print("B3=", B3.numpy())

#4-2:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      strides=2, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B4 = tf.pad(A, paddings=np.array([pads]))
print("B4=", B4.numpy())

#4-3:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=1, padding= 'casual')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B5 = tf.pad(A, paddings=np.array([pads]))
print("B5=", B5.numpy())

#4-4:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=2, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B6 = tf.pad(A, paddings=np.array([pads]))
print("B6=", B6.numpy())

#4-5:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=2, padding= 'casual')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B7 = tf.pad(A, paddings=np.array([pads]))
print("B7=", B7.numpy())

#4-6:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=3, padding= 'casual')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B8 = tf.pad(A, paddings=np.array([pads]))
print("B8=", B8.numpy())


new_k =2, new_steps=3, pads=(0, 1)
B1= [1. 2. 3. 4. 5. 0.]
new_k =4, new_steps=2, pads=(1, 1)
B2= [0. 1. 2. 3. 4. 5. 0.]
new_k =3, new_steps=5, pads=(1, 1)
B3= [0. 1. 2. 3. 4. 5. 0.]
new_k =3, new_steps=3, pads=(1, 1)
B4= [0. 1. 2. 3. 4. 5. 0.]
new_k =3, new_steps=5, pads=(2, 0)
B5= [0. 0. 1. 2. 3. 4. 5.]
new_k =5, new_steps=5, pads=(2, 2)
B6= [0. 0. 1. 2. 3. 4. 5. 0. 0.]
new_k =5, new_steps=5, pads=(4, 0)
B7= [0. 0. 0. 0. 1. 2. 3. 4. 5.]
new_k =7, new_steps=5, pads=(6, 0)
B8= [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5.]


##### 2차원 패딩

In [8]:
#36_03
import tensorflow as tf
import numpy as np
#1: crate a 2D input data
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]).astype('float32')
#2
pads = np.array([[1, 1],
                     [2, 2]])
#3
B = tf.pad(A, pads, "constant")
C = tf.pad(A, pads, "reflect")
D = tf.pad(A, pads, "symmetric")
print("B=", B.numpy())
print("C=", C.numpy())
print("D=", D.numpy())

B= [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 3. 0. 0.]
 [0. 0. 4. 5. 6. 0. 0.]
 [0. 0. 7. 8. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
C= [[6. 5. 4. 5. 6. 5. 4.]
 [3. 2. 1. 2. 3. 2. 1.]
 [6. 5. 4. 5. 6. 5. 4.]
 [9. 8. 7. 8. 9. 8. 7.]
 [6. 5. 4. 5. 6. 5. 4.]]
D= [[2. 1. 1. 2. 3. 3. 2.]
 [2. 1. 1. 2. 3. 3. 2.]
 [5. 4. 4. 5. 6. 6. 5.]
 [8. 7. 7. 8. 9. 9. 8.]
 [8. 7. 7. 8. 9. 9. 8.]]
