### 패딩
+ 데이터 확장하여 경계값 처리
+ constant : 양쪽으로 상수 붙임
+ reflect : 가운데 인덱스 값을 기준으로 반사
+ symmetric : 양쪽 끝 값 기준 반사

+ 1차원 데이터 패딩
+ 2차원 데이터 패딩

In [1]:
import tensorflow as tf
import numpy as np

##### 1차원 패딩
+ Reflect
    + last digit before the padding (경계 digit 제외하고 반사)
+ Symmetric
    + the boundary number first (경계 포함 반사)

In [5]:
#36_01
#1: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')

#2
p = 2
paddings = np.array([[p, p]])

#3
B = tf.pad(A, paddings, "constant") # 고정값으로 채움 (default 0)
C = tf.pad(A, paddings, "reflect") # 중앙값 기준 반사
D = tf.pad(A, paddings, "symmetric") # 양쪽 끝 기준 반사
print("B=", B.numpy())
print("C=", C.numpy())
print("D=", D.numpy())


B= [0. 0. 1. 2. 3. 4. 5. 0. 0.]
C= [3. 2. 1. 2. 3. 4. 5. 4. 3.]
D= [2. 1. 1. 2. 3. 4. 5. 5. 4.]


In [8]:
#36_02
#1:
def pad1d_infor(steps, kernel_size=2, strides=1,
                  dilation_rate=1, padding= 'valid'):
    k = (kernel_size-1)*dilation_rate + 1
    if padding == 'valid':
        new_steps = int(np.ceil((steps - k + 1) / strides))
        pad_left, pad_right=(0, 0)

    else: # 'same', 'casual'
        new_steps = int(np.ceil(steps/strides))
        pad_width = max((new_steps  - 1) * strides + k - steps, 0)

        if padding == 'same':
            pad_left  = pad_width//2
            pad_right = pad_width - pad_left
        if padding =='casual':
            pad_left  = pad_width
            pad_right = 0
    return k, new_steps, (pad_left, pad_right)

In [9]:
#2: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')
length = A.shape[0] #len(len), 5

```python
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=2, strides=2, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B1 = tf.pad(A, paddings=np.array([pads]))
print("B1=", B1.numpy())
```
+ B1= [1. 2. 3. 4. 5. 0.]

[1,    kernal_size = 2, strides = 2
2,          => (1,2), (3,4), (5,0) : new_steps : 3
3,
4,
5]


In [10]:
#3: padding in MaxPool1D [step37_02]
#3-1:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=2,
                                      strides=2, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B1 = tf.pad(A, paddings=np.array([pads]))
print("B1=", B1.numpy())

#3-2:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=4,
                                      strides=3, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B2 = tf.pad(A, paddings=np.array([pads]))
print("B2=", B2.numpy())

new_k =2, new_steps=3, pads=(0, 1)
B1= [1. 2. 3. 4. 5. 0.]
new_k =4, new_steps=2, pads=(1, 1)
B2= [0. 1. 2. 3. 4. 5. 0.]


In [12]:
#4: padding in Conv1D
#4-1:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B3 = tf.pad(A, paddings=np.array([pads]))
print("B3=", B3.numpy())

#4-2:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      strides=2, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B4 = tf.pad(A, paddings=np.array([pads]))
print("B4=", B4.numpy())

#4-3:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=1, padding= 'casual')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B5 = tf.pad(A, paddings=np.array([pads]))
print("B5=", B5.numpy())

#4-4:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=2, padding= 'same')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B6 = tf.pad(A, paddings=np.array([pads]))
print("B6=", B6.numpy())

#4-5:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=2, padding= 'casual')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B7 = tf.pad(A, paddings=np.array([pads]))
print("B7=", B7.numpy())

#4-6:
new_k, new_steps, pads= pad1d_infor(steps=length, kernel_size=3,
                                      dilation_rate=3, padding= 'casual')
print("new_k ={}, new_steps={}, pads={}".format(new_k,new_steps,pads))
B8 = tf.pad(A, paddings=np.array([pads]))
print("B8=", B8.numpy())

new_k =3, new_steps=5, pads=(1, 1)
B3= [0. 1. 2. 3. 4. 5. 0.]
new_k =3, new_steps=3, pads=(1, 1)
B4= [0. 1. 2. 3. 4. 5. 0.]
new_k =3, new_steps=5, pads=(2, 0)
B5= [0. 0. 1. 2. 3. 4. 5.]
new_k =5, new_steps=5, pads=(2, 2)
B6= [0. 0. 1. 2. 3. 4. 5. 0. 0.]
new_k =5, new_steps=5, pads=(4, 0)
B7= [0. 0. 0. 0. 1. 2. 3. 4. 5.]
new_k =7, new_steps=5, pads=(6, 0)
B8= [0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5.]


##### 2차원 패딩

In [13]:
#36_03
import tensorflow as tf
import numpy as np
#1: crate a 2D input data
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]).astype('float32')
#2
pads = np.array([[1, 1], #2차원 행의 --, ++
                     [2, 2]]) #2차원 열의 --. ++
#3
B = tf.pad(A, pads, "constant")
C = tf.pad(A, pads, "reflect") # 바운더리 제외 반사
D = tf.pad(A, pads, "symmetric") # 바운더리 기준 반사
print("B=", B.numpy())
print("C=", C.numpy())
print("D=", D.numpy())

B= [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 3. 0. 0.]
 [0. 0. 4. 5. 6. 0. 0.]
 [0. 0. 7. 8. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
C= [[6. 5. 4. 5. 6. 5. 4.]
 [3. 2. 1. 2. 3. 2. 1.]
 [6. 5. 4. 5. 6. 5. 4.]
 [9. 8. 7. 8. 9. 8. 7.]
 [6. 5. 4. 5. 6. 5. 4.]]
D= [[2. 1. 1. 2. 3. 3. 2.]
 [2. 1. 1. 2. 3. 3. 2.]
 [5. 4. 4. 5. 6. 6. 5.]
 [8. 7. 7. 8. 9. 9. 8.]
 [8. 7. 7. 8. 9. 9. 8.]]


In [15]:
#36_04
#1
def pad2d_infor(input_shape, kernel_size=(2,2), strides=(1,1),
                    dilation_rate=(1,1), padding= 'valid'):
    rows, cols = input_shape
    kH = (kernel_size[0]-1)*dilation_rate[0] + 1
    kW = (kernel_size[1]-1)*dilation_rate[1] + 1

    if padding == 'valid':
        new_rows = int(np.ceil((input_shape[0]-kH+1)/strides[0]))
        new_cols = int(np.ceil((input_shape[1]-kW+1)/strides[1]))
        pad_left, pad_right, pad_top, pad_bottom=(0, 0, 0, 0)

    else: # 'same'
        new_rows = int(np.ceil(input_shape[0]/strides[0]))
        new_cols = int(np.ceil(input_shape[1]/strides[1]))

        pad_height = max((new_rows-1)*strides[0] + kH - input_shape[0], 0)
        pad_width  = max((new_cols-1)*strides[1] + kW - input_shape[1], 0)

        pad_top    = pad_height//2
        pad_bottom = pad_height - pad_top
        pad_left  = pad_width//2
        pad_right = pad_width - pad_left
    return (kH,kW),(new_rows,new_cols),[[pad_left,pad_right],[pad_top,pad_bottom]]

In [18]:
#2: crate a 2D input data
A = np.array([[1, 2, 3, 4, 5],
              [4, 3, 2, 1, 0],
              [5, 6, 7, 8, 9],
              [4, 3, 2, 1, 0],
              [0, 1, 2, 3, 4]],dtype='float32')

#3: padding in 2D
#3-1:
new_k, new_shape, pads= pad2d_infor(input_shape=A.shape,
                                      kernel_size=(2,2), strides=(2,2), padding= 'valid')
print("new_k ={}, new_shape={}, pads={}".format(new_k, new_shape, pads))
B1 = tf.pad(A, paddings=np.array(pads))
print("B1=", B1.numpy())

#3-2:
new_k, new_shape, pads= pad2d_infor(input_shape=A.shape,
                         kernel_size=(2,2), strides=(2,2), padding= 'same')
print("new_k ={}, new_shape={}, pads={}".format(new_k, new_shape, pads))
B2 = tf.pad(A, paddings=np.array(pads))
print("B2=", B2.numpy())

new_k =(2, 2), new_shape=(2, 2), pads=[[0, 0], [0, 0]]
B1= [[1. 2. 3. 4. 5.]
 [4. 3. 2. 1. 0.]
 [5. 6. 7. 8. 9.]
 [4. 3. 2. 1. 0.]
 [0. 1. 2. 3. 4.]]
new_k =(2, 2), new_shape=(3, 3), pads=[[0, 1], [0, 1]]
B2= [[1. 2. 3. 4. 5. 0.]
 [4. 3. 2. 1. 0. 0.]
 [5. 6. 7. 8. 9. 0.]
 [4. 3. 2. 1. 0. 0.]
 [0. 1. 2. 3. 4. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
#36_05
#1: crate a 1D input data with 3-channels
A = np.array([1, 2, 3, 4, 5]).astype('float32')
print('A', A)
A = np.reshape(A, (1, -1, 1)) # (batch, steps, channels)
print('reshape: A', A, A.shape)


#2: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=A.shape[1:]))  # shape=(5, 1)
model.add(tf.keras.layers.ZeroPadding1D(padding=(1, 2)))
model.summary()

#3: apply A to model
output = model(A)
print("type(output) =", type(output))
print("output.numpy()=", output.numpy())

#4: apply A to model
output2 = model.predict(A)
print("type(output2) =", type(output2))
print("output2=", output2)


A [1. 2. 3. 4. 5.]
reshape: A [[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]] (1, 5, 1)
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 zero_padding1d_5 (ZeroPaddi  (None, 8, 1)             0         
 ng1D)                                                           
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
type(output) = <class 'tensorflow.python.framework.ops.EagerTensor'>
output.numpy()= [[[0.]
  [1.]
  [2.]
  [3.]
  [4.]
  [5.]
  [0.]
  [0.]]]
1/1 [==============================] - 0s 49ms/step
type(output2) = <class 'numpy.ndarray'>
output2= [[[0.]
  [1.]
  [2.]
  [3.]
  [4.]
  [5.]
  [0.]
  [0.]]]


In [28]:
#36_06
#1: crate a 2D input data
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]).astype('float32')
A = A.reshape(-1, 3, 3, 1)  # (batch, rows, cols, channels)
print(A, A.shape)

#2: build a model
pads = np.array([[1, 1],  # rows: (left, right) padding
                [2, 2]])  # cols: (top, bottom) padding
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=A.shape[1:]))  # (3,3,1)
model.add(tf.keras.layers.ZeroPadding2D(padding=pads))
model.summary()

#3: apply A to model
output = model(A)
print("output.shape=", output.shape) # 패딩 추가 되어서 (1, 5, 7, 1)
print("output.numpy()=", output.numpy())

#4: apply A to model
output2 = model.predict(A)
print("output2.shape=", output2.shape)
print("output2=", output2)


[[[[1.]
   [2.]
   [3.]]

  [[4.]
   [5.]
   [6.]]

  [[7.]
   [8.]
   [9.]]]] (1, 3, 3, 1)
Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 zero_padding2d_2 (ZeroPaddi  (None, 5, 7, 1)          0         
 ng2D)                                                           
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
output.shape= (1, 5, 7, 1)
output.numpy()= [[[[0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [1.]
   [2.]
   [3.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [4.]
   [5.]
   [6.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [7.]
   [8.]
   [9.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]
   [0.]]]]
1/1 [==============================] - 0s 29ms/step
output2.shape= (1, 5, 7, 1)
output2= [[[[0.]

### 1차원 풀링
+ 여러 개의 값을 하나의 값으로 다운 샘플링
+ MaxPooling1D
+ AveragePooling1D
+ GlobalMaxPooling1D
+ GlobalAveragePooling1D

In [33]:
#37_01 (padding = 'valid')
#1: GPU 메모리할당오류, [그림 2.9] 참조
#ref:https://www.tensorflow.org/guide/gpu

#gpus = tf.config.experimental.list_physical_devices('GPU')
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")

#tf.config.experimental.set_memory_growth(gpus[0], True)
#tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])

#2
# crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')

#3: calculate output size in padding = "valid"
k = 2           # pool_size, kernel_size
s = 2           # slides
n = len(A)      # input_size (=steps)
output_size= int(np.ceil((n - k + 1) / s))
print("A=", A, A.shape)
print("output_size = ", output_size)      # len(B)

A= [1. 2. 3. 4. 5.] (5,)
output_size =  2


In [34]:
#4: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape = (5, 1)))
model.add(tf.keras.layers.MaxPool1D())               # k = 2, s = 2
##model.add(tf.keras.layers.MaxPool1D(strides = 1) ) # k = 2, s = 1
##model.add(tf.keras.layers.Flatten())      # (batch, downsampled_steps * channels)
model.summary()

#5: apply A to model
A = np.reshape(A, (1, 5, 1))     # (batch, steps, channels)
output = model.predict(A)        # (batch, downsampled_steps, channels)

print("output=", output, output.shape)
B = output.flatten()
print("B=", B, B.shape)


Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 max_pooling1d_4 (MaxPooling  (None, 2, 1)             0         
 1D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 31ms/step
output= [[[2.]
  [4.]]] (1, 2, 1)
B= [2. 4.] (2,)


In [35]:
#2-1 k, s 변경
# crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')

#3: calculate output size in padding = "valid"
k = 2           # pool_size, kernel_size
s = 1           # slides
n = len(A)      # input_size (=steps)
output_size= int(np.ceil((n - k + 1) / s))
print("A=", A, A.shape)
print("output_size = ", output_size)      # len(B)

A= [1. 2. 3. 4. 5.] (5,)
output_size =  4


In [37]:
#4: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape = (5, 1)))
# model.add(tf.keras.layers.MaxPool1D())               # k = 2, s = 2
model.add(tf.keras.layers.MaxPool1D(strides = 1) ) # k = 2, s = 1
#model.add(tf.keras.layers.Flatten())      # (batch, downsampled_steps * channels)
model.summary()

#5: apply A to model
A = np.reshape(A, (1, 5, 1))     # (batch, steps, channels)
output = model.predict(A)        # (batch, downsampled_steps, channels)

print("output=", output, output.shape)
B = output.flatten()
print("B=", B, B.shape)


Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 max_pooling1d_6 (MaxPooling  (None, 4, 1)             0         
 1D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 27ms/step
output= [[[2.]
  [3.]
  [4.]
  [5.]]] (1, 4, 1)
B= [2. 3. 4. 5.] (4,)


In [38]:
#37_02 (MaxPool1D, "padding=same")
#1
#gpus = tf.config.experimental.list_physical_devices('GPU')
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")
#tf.config.experimental.set_memory_growth(gpus[0], True)

#2: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')

#3: calculate padding and output size(new_steps)
k = 2      # pool_size, kernel_size
s = 2      # slides
n = len(A) # input_size

# the same as pad1d_infor(padding="same")
new_steps = int(np.ceil(n/s))
print("new_steps = ", new_steps)

pad_width	= max((new_steps - 1) * s + k - n, 0)
pad_left	= pad_width // 2
pad_right	= pad_width - pad_left
print("pad_left = %s, pad_right=%s"%(pad_left, pad_right))

paddings = np.array([[pad_left, pad_right]])
B = tf.pad(A, paddings, "symmetric")
print("B=", B)

#4: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape = (5, 1)))
model.add(tf.keras.layers.MaxPool1D(pool_size = k, strides =s, padding="same"))
model.summary()

#5: apply A to model
A = np.reshape(A, (1, 5, 1)) # (batch, steps, channels)
output = model.predict(A) # (batch, downsampled_steps, channels)
C = output.flatten()
print("C=", C)


new_steps =  3
pad_left = 0, pad_right=1
B= tf.Tensor([1. 2. 3. 4. 5. 5.], shape=(6,), dtype=float32)
Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 max_pooling1d_7 (MaxPooling  (None, 3, 1)             0         
 1D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 28ms/step
C= [2. 4. 5.]


In [39]:
#37_03 (AveragePool1D, padding='valid')
#1
#gpus = tf.config.experimental.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(gpus[0], True)
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")
#2: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')

#3: calculate output size in padding="valid"
k = 2      # pool_size, kernel_size
s = 2      # slides
n = len(A) # input_size
# the same as pad1d_infor(padding="valid")
new_steps= int(np.ceil((n - k + 1) / s))
print("new_steps = ", new_steps) # len(B)

#4: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(5, 1)))
model.add(tf.keras.layers.AveragePooling1D(pool_size=k, strides =s))
model.summary()

#5: apply A to model
A = np.reshape(A, (1, 5, 1)) # (batch, steps, channels)
output = model.predict(A)    # (batch, downsampled_steps, channels)
B = output.flatten()
print("B=", B)


new_steps =  2
Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 average_pooling1d (AverageP  (None, 2, 1)             0         
 ooling1D)                                                       
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 316ms/step
B= [1.5 3.5]


In [41]:
#37_04 (AveragePool1D, padding='same')
#1
#gpus = tf.config.experimental.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(gpus[0], True)
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")
#2: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')

#3: calculate padding and output size(new_steps)
k = 2      # pool_size, kernel_size
s = 2      # slides
n = len(A) # input_size

# the same as pad1d_infor(padding="same")
new_steps = int(np.ceil(n/s))
print("new_steps  = ", new_steps ) # len(C)

pad_width	= max((new_steps - 1) * s + k - n, 0)
pad_left	= pad_width // 2
pad_right	= pad_width - pad_left
print("pad_left = %s, pad_right=%s"%(pad_left, pad_right))

paddings = np.array([[pad_left, pad_right]])
B = tf.pad(A, paddings) # 0-padding, but mode don't care, not used padding values
print("B=", B)

#4: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape = (5, 1)))
model.add(tf.keras.layers.AveragePooling1D(pool_size = k, strides =s, padding="same"))
model.summary()

#5: apply A to model
A = np.reshape(A, (1, 5, 1)) # (batch, steps, channels)
output = model.predict(A)    # (batch, downsampled_steps, channels)
C = output.flatten()
print("C=", C)

new_steps  =  3
pad_left = 0, pad_right=1
B= tf.Tensor([1. 2. 3. 4. 5. 0.], shape=(6,), dtype=float32)
Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 average_pooling1d_2 (Averag  (None, 3, 1)             0         
 ePooling1D)                                                     
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 27ms/step
C= [1.5 3.5 5. ]


In [42]:
#37_05 (1차원 다채널 데이터 풀링)
#1
#gpus = tf.config.experimental.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(gpus[0], True)
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")
#2: crate a 1D input data with 3-channels
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3],
              [4, 4, 4],
              [5, 5, 5]], dtype='float32')
A = np.expand_dims(A, axis=0) # shape = ([1, 5, 3])

#3: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape = (5, 3)))
model.add(tf.keras.layers.MaxPool1D()) #pool_size = 2, strides =2 padding='valid'
##model.add(tf.keras.layers.AveragePooling1D())
##model.add(tf.keras.layers.MaxPool1D(padding='same')
##model.add(tf.keras.layers.AveragePooling1D(padding='same'))
##model.summary()

#4: apply A to model
B = model.predict(A) # (batch, downsampled_steps, channels)
print("B=", B)
print("B[:,:,0]=", B[:,:,0]) # 0-channel R
print("B[:,:,1]=", B[:,:,1]) # 1-channel G
print("B[:,:,2]=", B[:,:,2]) # 2-channel B


1/1 [==============================] - 0s 25ms/step
B= [[[2. 2. 2.]
  [4. 4. 4.]]]
B[:,:,0]= [[2. 4.]]
B[:,:,1]= [[2. 4.]]
B[:,:,2]= [[2. 4.]]


In [44]:
#37_06 GlobalMaxPooling1D
#1
##gpus = tf.config.experimental.list_physical_devices('GPU')
##tf.config.experimental.set_memory_growth(gpus[0], True)

#2: crate a 1D input data with 3-channels
A = np.array([[1, 0, 0],
              [2, 4, 0],
              [3, 3, 3],
              [4, 2, 2],
              [5, 1, 1]], dtype='float32')
A = np.expand_dims(A, axis=0) # (batch, steps, channels)= ([1, 5, 3])

#3: build a model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(5, 3)))
model.add(tf.keras.layers.GlobalMaxPooling1D())
# model.add(tf.keras.layers.GlobalAveragePooling1D())
model.summary()

#4: apply A to model
output = model.predict(A)   # (batch, channels) = (1, 3)
print("output=", output)


Model: "sequential_22"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 global_max_pooling1d (Globa  (None, 3)                0         
 lMaxPooling1D)                                                  
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 54ms/step
output= [[5. 4. 3.]]


### 1차원 합성곱
+ 커널(가중치)과 내적으로 계산

In [45]:
#38_01
#1
#gpus = tf.config.experimental.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(gpus[0], True)
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")
#2: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')
A = np.reshape(A, (1, 5, 1))  #  (batch, steps, channels)

#3: build a model
KERNEL_SIZE = 3
STRIDE      = 1
PADDING  = 'valid'  # 'same’

model = tf.keras.Sequential()
##model.add(tf.keras.layers.Input(shape = A.shape[1:])) # (5, 1)
##model.add(tf.keras.layers.Conv1D(filters=1,
##                                 kernel_size = KERNEL_SIZE,
##                                 strides= STRIDE,
##                                 padding= PADDING,
##                                 use_bias=False,
##                                 kernel_initializer=tf.constant_initializer(1),
##                                 ))
model.add(tf.keras.layers.Conv1D(filters=1,
                                 kernel_size = KERNEL_SIZE,
                                 strides= STRIDE,
                                 padding= PADDING,
                                 use_bias=False,
                                 kernel_initializer=tf.constant_initializer(1),
                                 input_shape=A.shape[1:])) # (5, 1)
model.summary()

#4: apply A to model
output = model.predict(A) # output.shape : (batch, new_steps, filters)
B = output.flatten()       # B = tf.reshape(output,[-1]).numpy()
print("B=", B)


Model: "sequential_23"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 3, 1)              3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 185ms/step
B= [ 6.  9. 12.]


##### dilation_rate

In [ ]:
#38_02 (filter=1, dilation_rate=2, padding='casual')
#1
#gpus = tf.config.experimental.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(gpus[0], True)
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")
#2: crate a 1D input data
A = np.array([1, 2, 3, 4, 5]).astype('float32')
A = np.reshape(A, (1, 5, 1)) # (batch, steps, channels)

#3: build a model
KERNEL_SIZE = 3
DILATE = 1          # 1, 2, 3
PADDING  = 'causal'  # 'valid' 'same’
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv1D(filters=1,
                                 kernel_size = KERNEL_SIZE,
                                 strides= 1,
                                 padding= PADDING,
                                 dilation_rate=DILATE,
                                 use_bias=False,
                                 kernel_initializer=tf.constant_initializer(1),
                                 input_shape=A.shape[1:])) # (5, 1)
model.add(tf.keras.layers.Flatten())
model.summary()

#4: apply A to model
B = model.predict(A)   # B.shape : (batch, new_steps*filters)
print("B=", B)


In [46]:
#38_03 (Conv1D)
#1
#gpus = tf.config.experimental.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(gpus[0], True)
#if gpus:
#    for gpu in gpus:
#        tf.config.experimental.set_memory_growth(gpu,True)
#else:
#    print("No GPU found")

#2: crate a 1D input data
A = np.array([[1, 2, 3, 4, 5],
              [1, 1, 1, 1, 1],
              [1, 2, 0, 1, 2]], dtype='float32') # batch = 3 (3개의 1차원 데이터)
n = 2 # number of neurons in Dense, # of filters in Conv1D
steps = A.shape[1] # length, 5

#3: kernel initial values, shape: (5, 2)
W = np.array([[1., 2.],
              [1., 2.],
              [1., 2.],
              [1., 2.],
              [1., 2.]], dtype="float")

#4: Dense with n units, input_dim = steps
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=steps ))
model.add(tf.keras.layers.Dense(units=n, use_bias=False , # input_dim=steps,
                                 kernel_initializer=tf.constant_initializer(W)))
model.summary()
print("model.trainable_variables=", model.trainable_variables)

# apply A to model
##output = model(A)      # tensor, output.shape= (3, 2)
output = model.predict(A) # numpy, output.shape= (3, 2)
print("output=", output)

#5: Conv1D with n filters, kernel_size =steps, strides = 1, input shape=(steps,1)
model2 = tf.keras.Sequential()
model2.add(tf.keras.layers.Input(shape=(steps,1)))
model2.add(tf.keras.layers.Conv1D(filters = n, kernel_size = steps, use_bias=False,                                        kernel_initializer= tf.constant_initializer(W)))
model2.add(tf.keras.layers.Flatten()) # output.shape : (batch, new_steps*filters)
model2.summary()
print("model2.trainable_variables=", model2.trainable_variables)

# apply A to model2
A2 = np.expand_dims(A, axis=2) # tf.expand_dims(A, axis=2), shape = ([3, 5, 1])
##print("A2 = ", A2)
output2 = model2.predict(A2) # output2.shape= (3, 2)
print("output2=", output2)


Model: "sequential_24"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 10        
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
model.trainable_variables= [<tf.Variable 'dense/kernel:0' shape=(5, 2) dtype=float32, numpy=
array([[1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [1., 2.]], dtype=float32)>]
1/1 [==============================] - 0s 301ms/step
output= [[15. 30.]
 [ 5. 10.]
 [ 6. 12.]]
Model: "sequential_25"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_1 (Conv1D)           (None, 1, 2)              10        
                                                                 
 flatte

In [51]:
#38_04 (3채널 데이터)
#2: crate a 1D input data
A = np.array([[1, 1, 1],
              [2, 1, 2],
              [3, 1, 0],
              [4, 1, 1],
              [5, 1, 2]], dtype='float32')
n = 2 # number of filters in Conv1D
steps = 5 # A.shape[0], 5, length

#3: kernel initial values, channels
W0 = np.ones(shape=(5, 3), dtype='float32')
W1 = np.full(shape=(5, 3), fill_value=2.0, dtype='float32')
W = np.stack((W0, W1), axis=2) # (5, 3, 2)

#4: Conv1D with n filters,  kernel_size =steps, strides = 1,
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(steps, 3)))
model.add(tf.keras.layers.Conv1D(filters= n, kernel_size= steps, use_bias= False,
                                 kernel_initializer= tf.constant_initializer(W)))
model.add(tf.keras.layers.Flatten()) # output.shape : (batch, new_steps*filters)
model.summary()

#5: apply A to model
A = np.expand_dims(A, axis=0) # tf.expand_dims(A, axis=0), shape = ([1, 5, 3])
print("A = ", A)

output = model.predict(A) # output.shape =(1, 2)
print("output=", output)

##w = model.trainable_variables[0].numpy()
##print("w[:,:,0]=", w[:,:,0]) # W[:,:,0]
##print("w[:,:,1]=", w[:,:,1]) # W[:,:,1]


Model: "sequential_26"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_2 (Conv1D)           (None, 1, 2)              30        
                                                                 
 flatten_1 (Flatten)         (None, 2)                 0         
                                                                 
Total params: 30
Trainable params: 30
Non-trainable params: 0
_________________________________________________________________
A =  [[[1. 1. 1.]
  [2. 1. 2.]
  [3. 1. 0.]
  [4. 1. 1.]
  [5. 1. 2.]]]
1/1 [==============================] - 0s 52ms/step
output= [[26. 52.]]
